### ISSUE TITLE
The sitemap link in the readme file is dead

### ISSUE THREAD

**Issue by AKuederle** [joshualande/joshualande.github.io#9]
The Link to the sitemap blog post, does not work anymore

**Comment by joshualande** [comment]
I can't find the issue. Can you reopen providing more information?

**Comment by AKuederle** [comment]
You linked to another Blogpost in the README of this repository (not in your blog)
```
The sitemap.xml file was inspired by this post.
```
The link there is dead. I don't if the site just doesn't exists anymore, or if something else went wrong

**Comment by joshualande** [comment]
Thanks for the clarification. I removed the dead link!
